type UnwrappedTheme = {
  background: string;
  card: string;
  cardActive: string;
  cardActiveAlt: string;
  cardInactive: string;
  iconBackground: string;
  cardDark: string;
  primary: string;
  fontStd: string;
  fontLight: string;
  fontMedium: string;
  fontInverse: string;
  text: string;
  border: string;
  notification: string;
  avatarBackgrounds: string[];
  onCardActive: string;
};
export default UnwrappedTheme;
